# -*- coding: utf-8 -*-
"""PracticePythonBeginnerLessons.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8H_tlWEn7MJ3AfMLyxzodJKnP9NComT
"""

## 100_Yrs_old Program
# Aks the user to enter their name and their age.
user_input_name = input("Enter your name: ")

print(user_input_name)

user_input_turning_age = input("Enter your age you have turned to or are turning this calendar year: ")

year_will_be_100 = 2022 + (100 -int(user_input_age))#why is the year off

print(year_will_be_100)

print("In the year " + str(year_will_be_100) + " you will turn 100 years of age.")


#print('You will be' + )


#birth_year = int(user_input_age)- 2021
#birth_year = 2021 - int(user_input_age)
#print(birth_year)




#year_100_years = int(user_input_age) +90
#print(year_100_years)

# Reads "Hi, Jessica. In the year ___, you will be 100 years old."



1) program 8:11 - Accept. Report. Analyze. Plan next steps. Do. (Forgot Mitch singing and forgot to start break times so i losr track of it. R - Mitch sing

9:04 timer also had issue, so lets use kitchen timer



next 17 min goal, do part 2

goal learn to  

2) eat sandwhich, all away
3) wash clothes
4) plan next 3 days sleep. (2 week goals and busget; plan time)
   -go to mosque 2 times and make 2 friends
   -clean tub

am visit to pemberton after some work
big breakfast make


syllabus
   showcase
   solidify
   sticktoit